version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: cpsc304-mysql
      working_dir: /var/www
      volumes:
        - './application:/var/www'
        - './data/mysql:/var/lib/mysql'
        - './data/mysql-dump:/docker-entrypoint-initdb.d'
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=database
        - MYSQL_USER=root
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: cpsc304-webserver
      working_dir: /var/www
      volumes:
        - './application:/var/www'
        - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      ports:
       - "8080:80"

    php-fpm:
      build: ./php-fpm
      container_name: cpsc304-php-fpm
      working_dir: /var/www
      volumes:
        - './application:/var/www'
        - './php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: cpsc304-phpmyadmin
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - 8000:80
      links:
        - mysql

